version: '3.9'

services:
  wordpress:
    image: mirror.gcr.io/wordpress:6.8.1-php8.1-apache
    container_name: wp-app
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mirror.gcr.io/mariadb:11.8.1-ubi9-rc
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data: